name: CI
on:
  push:
    branches: [ main ]
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r backend/requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest || true  # 現状テストなし